package com.lighthousepark.intervalsgym.app

internal const val PREFS_NAME = "intervals_gym"
internal const val LEGACY_INTERVALS_CREDENTIAL_PREF = "intervals_api_key"
internal const val INTERVALS_LOGIN_PROMPT_SEEN_PREF = "intervals_login_prompt_seen"
internal const val STRENGTH_ROUTINES_PREF = "strength_routines"
internal const val ACTIVE_STRENGTH_SESSION_PREF = "active_strength_session"
internal const val STRENGTH_SESSION_HISTORY_PREF = "strength_session_history"
internal const val RUNNING_SESSION_HISTORY_PREF = "running_session_history"
internal const val SAVED_RUNNING_ROUTINES_PREF = "saved_running_routines"
internal const val SCHEDULED_STRENGTH_ROUTINES_PREF = "scheduled_strength_routines"
internal const val INTERVALS_OAUTH_TOKEN_PREF = "intervals_oauth_token"
internal const val INTERVALS_OAUTH_STATE_PREF = "intervals_oauth_state"
internal const val INTERVALS_GYM_STRENGTH_ROUTINE_PREFIX = "INTERVALS_GYM_STRENGTH_ROUTINE:"
internal const val INTERVALS_GYM_STRENGTH_ROUTINE_ID_PREFIX = "INTERVALS_GYM_STRENGTH_ROUTINE_ID:"
