package com.lighthousepark.intervalsgym.core

internal object AppColorPalette {
    const val TRANSPARENT = 0x00000000L
    const val BACKGROUND = 0xFF08090BL
    const val SURFACE = 0xFF1A1D23L
    const val SURFACE_HIGH = 0xFF242830L
    const val SURFACE_BRIGHT = 0xFF323740L
    const val SURFACE_CONTAINER_LOWEST = 0xFF0B0C0FL
    const val SURFACE_CONTAINER_LOW = 0xFF14161AL
    const val SURFACE_CONTAINER = 0xFF1C1F25L
    const val SURFACE_CONTAINER_HIGH = 0xFF252A32L
    const val SURFACE_CONTAINER_HIGHEST = 0xFF303640L

    const val HIGHLIGHT = 0xFFFF4E01L
    const val HIGHLIGHT_CONTAINER = 0xFF3A1609L
    const val ON_HIGHLIGHT_CONTAINER = 0xFFFFDCCFL
    const val COOL_ACCENT = 0xFF95ABE0L
    const val COOL_ACCENT_MUTED = 0xFFB6C8F2L
    const val COOL_CONTAINER = 0xFF1B263AL
    const val ON_COOL_CONTAINER = 0xFFDCE6FFL

    const val SUCCESS = 0xFF5DDA78L
    const val SUCCESS_SOFT = 0xFF183720L
    const val DANGER = 0xFFFF6B4AL
    const val DANGER_CONTAINER = 0xFF441813L
    const val ON_DANGER_CONTAINER = 0xFFFFDAD3L

    const val TEXT = 0xFFF4F3F6L
    const val TEXT_MUTED = 0xFFB9BBC4L
    const val OUTLINE = 0xFF858A94L
    const val OUTLINE_SOFT = 0xFF343840L
    const val INVERSE_SURFACE = 0xFFE6E2E5L
    const val INVERSE_TEXT = 0xFF2E3035L
    const val SCRIM = 0xFF000000L

    const val GRAPH_BACKGROUND = SURFACE
    const val GRAPH_GRID = 0xFF57392CL
    const val GRAPH_LABEL = 0xFFCDBCB5L
    const val GRAPH_THRESHOLD = 0xFF9D6D59L
    const val GRAPH_INACTIVE = 0xFF6B4536L
    const val GRAPH_ORANGE_1 = 0xFFFFD1B8L
    const val GRAPH_ORANGE_2 = 0xFFFFB087L
    const val GRAPH_ORANGE_3 = 0xFFFF9561L
    const val GRAPH_ORANGE_4 = 0xFFFF7A3DL
    const val GRAPH_ORANGE_5 = 0xFFFF5D18L
    const val GRAPH_ORANGE_6 = HIGHLIGHT
    const val GRAPH_ORANGE_7 = 0xFFD83A00L
    const val GRAPH_ACTIVE = 0xFFFFB15CL
    const val GRAPH_HEART_RATE = 0xFFFF6424L
    const val GRAPH_ROUTE_BACKGROUND = 0xFF21120CL
    const val GRAPH_ROUTE_LAND = 0xFF8A4B2CL
    const val GRAPH_ROUTE_START = GRAPH_ORANGE_2
    const val GRAPH_ROUTE_FINISH = GRAPH_ORANGE_7

    const val OVERLAY_TEXT = 0xFFFFFFFFL
    const val OVERLAY_TEXT_MUTED = 0xDDFFFFFFL
    const val OVERLAY_BACKGROUND = 0xE6111318L
    const val OVERLAY_URGENT_BACKGROUND = 0xE6A72C00L
    const val OVERLAY_ACTION_BACKGROUND = HIGHLIGHT
}
