package com.lighthousepark.intervalsgym.core

import androidx.compose.ui.Modifier
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.semantics
import com.lighthousepark.intervalsgym.BuildConfig
import java.time.LocalDate

internal object TestContentDescriptions {
    const val StrengthStartWorkout = "test-strength-start-workout"
    const val StrengthEditWorkoutRoutine = "test-strength-edit-workout-routine"
    const val StrengthSessionBack = "test-strength-workout-back"
    const val StrengthSessionHistory = "test-strength-workout-history"
    const val StrengthSessionCalendarRoutineDelete = "test-strength-workout-calendar-routine-delete"
    const val StrengthSessionCalendarRoutineConfirmDelete = "test-strength-workout-calendar-routine-confirm-delete"
    const val StrengthSessionCalendarRoutineCancelDelete = "test-strength-workout-calendar-routine-cancel-delete"
    const val StrengthAddExercise = "test-strength-add-exercise"
    const val StrengthGroupSuperset = "test-strength-group-superset"
    const val StrengthConfirmSuperset = "test-strength-confirm-superset"
    const val StrengthClearSuperset = "test-strength-clear-superset"
    const val StrengthCancelSuperset = "test-strength-cancel-superset"
    const val StrengthCompleteSet = "test-strength-complete-set"
    const val StrengthResumeWorkoutExercise = "test-strength-resume-workout-exercise"
    const val StrengthFinishWorkout = "test-strength-finish-workout"
    const val StrengthFinishSave = "test-strength-finish-save"
    const val StrengthFinishDiscard = "test-strength-finish-discard"
    const val StrengthFinishUpdateOrder = "test-strength-finish-update-order"
    const val StrengthFinishUpdateSupersets = "test-strength-finish-update-supersets"
    const val StrengthFinishUpdateExerciseTypes = "test-strength-finish-update-exercise-types"
    const val StrengthFinishUpdateExerciseDetails = "test-strength-finish-update-exercise-details"
    const val StrengthUploadWorkout = "test-strength-upload-workout"
    const val StrengthRestStop = "test-strength-rest-stop"
    const val StrengthRestFloatingChip = "test-strength-rest-floating-chip"
    const val StrengthSetExecutionExercise = "test-strength-set-execution-exercise"
    const val StrengthSetExecutionAddSet = "test-strength-set-execution-add-set"
    const val StrengthExerciseSearch = "test-strength-exercise-search"
    const val StrengthCreateExercise = "test-strength-create-exercise"
    const val StrengthRoutineListBack = "test-strength-routine-list-back"
    const val StrengthRoutineListManage = "test-strength-routine-list-manage"
    const val StrengthRoutineListEmpty = "test-strength-routine-list-empty"
    const val StrengthRoutineManagementBack = "test-strength-routine-management-back"
    const val StrengthRoutineManagementAdd = "test-strength-routine-management-add"
    const val StrengthRoutineManagementEmpty = "test-strength-routine-management-empty"
    const val StrengthRoutineEditBack = "test-strength-routine-edit-back"
    const val StrengthRoutineEditName = "test-strength-routine-edit-name"
    const val StrengthRoutineEditGroupSuperset = "test-strength-routine-edit-group-superset"
    const val StrengthRoutineEditAddExercise = "test-strength-routine-edit-add-exercise"
    const val StrengthRoutineEditSave = "test-strength-routine-edit-save"
    const val StrengthRoutineEditDelete = "test-strength-routine-edit-delete"
    const val StrengthRoutineEditConfirmDelete = "test-strength-routine-edit-confirm-delete"
    const val StrengthRoutineEditCancelDelete = "test-strength-routine-edit-cancel-delete"
    const val StrengthRoutineEditSaveUnsaved = "test-strength-routine-edit-save-unsaved"
    const val StrengthRoutineEditDiscardUnsaved = "test-strength-routine-edit-discard-unsaved"
    const val StrengthRoutineEditCancelUnsaved = "test-strength-routine-edit-cancel-unsaved"
    const val StrengthExerciseDetailChangeType = "test-strength-exercise-detail-change-type"
    const val StrengthExerciseDetailChangeExercise = "test-strength-exercise-detail-change-exercise"
    const val StrengthExerciseDetailAddSet = "test-strength-exercise-detail-add-set"
    const val StrengthExerciseDetailAddExercise = "test-strength-exercise-detail-add-exercise"
    const val StrengthExerciseDetailDeleteExercise = "test-strength-exercise-detail-delete-exercise"
    const val StrengthExerciseDetailCancel = "test-strength-exercise-detail-cancel"
    const val StrengthExerciseDetailSave = "test-strength-exercise-detail-save"
    const val StrengthExerciseConfigDone = "test-strength-exercise-config-done"
    const val StrengthExerciseConfigCancel = "test-strength-exercise-config-cancel"
    const val StrengthCustomExerciseName = "test-strength-custom-exercise-name"
    const val StrengthCustomExerciseAdd = "test-strength-custom-exercise-add"
    const val StrengthCustomExerciseCancel = "test-strength-custom-exercise-cancel"
    const val StrengthHistoryBack = "test-strength-history-back"

    const val WorkoutRoutineBack = "test-workout-routine-back"
    const val WorkoutRoutineStartWorkout = "test-workout-routine-start-workout"
    const val WorkoutRoutineSaveRunning = "test-workout-routine-save-running"
    const val WorkoutRoutineHeartRate = "test-workout-routine-heart-rate"
    const val WorkoutRoutineDelete = "test-workout-routine-delete"
    const val WorkoutRoutineConfirmDelete = "test-workout-routine-confirm-delete"
    const val WorkoutRoutineCancelDelete = "test-workout-routine-cancel-delete"
    const val WorkoutRoutineUploadLocalWorkout = "test-workout-routine-upload-local-workout"
    const val RunningTimerToggle = "test-running-timer-toggle"
    const val RunningTimerReset = "test-running-timer-reset"
    const val WorkoutErrorRetry = "test-workout-error-retry"
    const val HeartRatePickerRescan = "test-heart-rate-picker-rescan"
    const val HeartRatePickerDisconnect = "test-heart-rate-picker-disconnect"
    const val HeartRatePickerDismiss = "test-heart-rate-picker-dismiss"

    const val LoginOAuth = "test-login-oauth"
    const val LoginSkip = "test-login-skip"

    const val RunningRoutineListManage = "test-running-routine-list-manage"
    const val RunningRoutineListBack = "test-running-routine-list-back"
    const val RunningRoutineListEmpty = "test-running-routine-list-empty"
    const val RunningRoutineManagementBack = "test-running-routine-management-back"
    const val RunningRoutineManagementEmpty = "test-running-routine-management-empty"
    const val RunningRoutineDelete = "test-running-routine-delete"
    const val RunningRoutineConfirmDelete = "test-running-routine-confirm-delete"
    const val RunningRoutineCancelDelete = "test-running-routine-cancel-delete"
    const val RunningSessionBack = "test-running-workout-back"
    const val RunningPrimaryAction = "test-running-primary-action"
    const val RunningPreviousBlock = "test-running-previous-block"
    const val RunningStopWorkout = "test-running-stop-workout"
    const val RunningStopSave = "test-running-stop-save"
    const val RunningStopDiscard = "test-running-stop-discard"
    const val RunningFinishUpload = "test-running-finish-upload"
    const val RunningFinishUseGarmin = "test-running-finish-use-garmin"
    const val RunningFinishClose = "test-running-finish-close"
    const val RunningConnectHeartRate = "test-running-connect-heart-rate"
    const val LocalRunningSessionDelete = "test-local-running-workout-delete"

    const val TrainingCalendarFabMenu = "test-training-calendar-fab-menu"
    const val TrainingCalendarBack = "test-training-calendar-back"
    const val TrainingCalendarMode = "test-training-calendar-mode"
    const val TrainingCalendarSettings = "test-training-calendar-settings"
    const val TrainingCalendarRefresh = "test-training-calendar-refresh"
    const val TrainingCalendarIntervalsAuth = "test-training-calendar-intervals-auth"
    const val TrainingActionRunning = "test-training-action-running"
    const val TrainingActionStrength = "test-training-action-strength"
    const val StrengthRoutineSaveDate = "test-strength-routine-save-date"
    const val StrengthRoutineSaveTime = "test-strength-routine-save-time"

    fun strengthReadyEntry(entryId: Int): String = "test-strength-ready-entry-$entryId"
    fun strengthOngoingEntry(entryId: Int): String = "test-strength-ongoing-entry-$entryId"
    fun strengthSupersetEntryToggle(entryId: Int): String = "test-strength-superset-entry-toggle-$entryId"
    fun strengthSupersetEntryLabel(entryId: Int): String = "test-strength-superset-entry-label-$entryId"
    fun strengthExerciseSearchResult(exerciseId: String): String = "test-strength-exercise-result-$exerciseId"
    fun strengthRoutineListRow(routineId: Int): String = "test-strength-routine-list-row-$routineId"
    fun strengthRoutineListStart(routineId: Int): String = "test-strength-routine-list-start-$routineId"
    fun strengthRoutineManagementEdit(routineId: Int): String = "test-strength-routine-management-edit-$routineId"
    fun strengthRoutineExerciseRow(entryId: Int): String = "test-strength-routine-exercise-row-$entryId"
    fun strengthRoutineExerciseRestore(entryId: Int): String = "test-strength-routine-exercise-restore-$entryId"
    fun strengthHistoryRow(sessionId: String): String = "test-strength-history-row-$sessionId"
    fun strengthSessionSetDetail(entryId: Int, setRecordId: Int): String = "test-strength-workout-set-detail-$entryId-$setRecordId"
    fun strengthSetRecordRow(setRecordId: Int): String = "test-strength-set-record-row-$setRecordId"
    fun strengthPlannedSetRecord(setRecordId: Int): String = "test-strength-planned-set-record-$setRecordId"
    fun strengthPlannedSetWeight(setRecordId: Int): String = "test-strength-planned-set-weight-$setRecordId"
    fun strengthPlannedSetReps(setRecordId: Int): String = "test-strength-planned-set-reps-$setRecordId"
    fun strengthActualSetRecord(setRecordId: Int): String = "test-strength-actual-set-record-$setRecordId"
    fun strengthActualSetWeight(setRecordId: Int): String = "test-strength-actual-set-weight-$setRecordId"
    fun strengthActualSetReps(setRecordId: Int): String = "test-strength-actual-set-reps-$setRecordId"
    fun strengthChoiceOption(title: String, option: String): String = "test-strength-choice-$title-$option"
    fun strengthRestTimeControl(label: String): String = "test-strength-rest-time-$label"
    fun runningTargetStepper(label: String, direction: String): String = "test-running-target-stepper-$label-$direction"
    fun runningSavedRoutine(routineId: String): String = "test-running-saved-routine-$routineId"
    fun trainingCalendarFabAction(text: String): String = "test-training-calendar-fab-action-$text"
    fun monthlyCalendarDay(day: LocalDate): String = "test-monthly-calendar-day-$day"
    fun monthlyCalendarItem(itemId: String): String = "test-monthly-calendar-item-$itemId"
    fun strengthRoutineSaveRow(routineId: Int): String = "test-strength-routine-save-row-$routineId"
}

internal fun Modifier.debugContentDescription(description: String): Modifier {
    return if (BuildConfig.DEBUG) {
        semantics { contentDescription = description }
    } else {
        this
    }
}
