package com.lighthousepark.intervalsgym.core

import androidx.compose.ui.Modifier
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.semantics
import com.lighthousepark.intervalsgym.BuildConfig
import java.time.LocalDate

internal object TestContentDescriptions {
    const val StrengthStartWorkout = "test-strength-start-workout"
    const val StrengthEditWorkoutPlan = "test-strength-edit-workout-plan"
    const val StrengthWorkoutBack = "test-strength-workout-back"
    const val StrengthWorkoutHistory = "test-strength-workout-history"
    const val StrengthWorkoutCalendarPlanDelete = "test-strength-workout-calendar-plan-delete"
    const val StrengthWorkoutCalendarPlanConfirmDelete = "test-strength-workout-calendar-plan-confirm-delete"
    const val StrengthWorkoutCalendarPlanCancelDelete = "test-strength-workout-calendar-plan-cancel-delete"
    const val StrengthAddExercise = "test-strength-add-exercise"
    const val StrengthGroupSuperset = "test-strength-group-superset"
    const val StrengthConfirmSuperset = "test-strength-confirm-superset"
    const val StrengthClearSuperset = "test-strength-clear-superset"
    const val StrengthCancelSuperset = "test-strength-cancel-superset"
    const val StrengthCompleteSet = "test-strength-complete-set"
    const val StrengthFinishWorkout = "test-strength-finish-workout"
    const val StrengthFinishSave = "test-strength-finish-save"
    const val StrengthFinishDiscard = "test-strength-finish-discard"
    const val StrengthFinishApplyToPlan = "test-strength-finish-apply-to-plan"
    const val StrengthUploadWorkout = "test-strength-upload-workout"
    const val StrengthRestStop = "test-strength-rest-stop"
    const val StrengthRestFloatingChip = "test-strength-rest-floating-chip"
    const val StrengthSetExecutionExercise = "test-strength-set-execution-exercise"
    const val StrengthSetExecutionAddSet = "test-strength-set-execution-add-set"
    const val StrengthExerciseSearch = "test-strength-exercise-search"
    const val StrengthCreateExercise = "test-strength-create-exercise"
    const val StrengthPlanListBack = "test-strength-plan-list-back"
    const val StrengthPlanListManage = "test-strength-plan-list-manage"
    const val StrengthPlanListEmpty = "test-strength-plan-list-empty"
    const val StrengthPlanManagementBack = "test-strength-plan-management-back"
    const val StrengthPlanManagementAdd = "test-strength-plan-management-add"
    const val StrengthPlanManagementEmpty = "test-strength-plan-management-empty"
    const val StrengthPlanEditBack = "test-strength-plan-edit-back"
    const val StrengthPlanEditName = "test-strength-plan-edit-name"
    const val StrengthPlanEditGroupSuperset = "test-strength-plan-edit-group-superset"
    const val StrengthPlanEditAddExercise = "test-strength-plan-edit-add-exercise"
    const val StrengthPlanEditSave = "test-strength-plan-edit-save"
    const val StrengthPlanEditDelete = "test-strength-plan-edit-delete"
    const val StrengthPlanEditConfirmDelete = "test-strength-plan-edit-confirm-delete"
    const val StrengthPlanEditCancelDelete = "test-strength-plan-edit-cancel-delete"
    const val StrengthPlanEditSaveUnsaved = "test-strength-plan-edit-save-unsaved"
    const val StrengthPlanEditDiscardUnsaved = "test-strength-plan-edit-discard-unsaved"
    const val StrengthPlanEditCancelUnsaved = "test-strength-plan-edit-cancel-unsaved"
    const val StrengthExerciseDetailChangeType = "test-strength-exercise-detail-change-type"
    const val StrengthExerciseDetailChangeExercise = "test-strength-exercise-detail-change-exercise"
    const val StrengthExerciseDetailAddSet = "test-strength-exercise-detail-add-set"
    const val StrengthExerciseDetailAddExercise = "test-strength-exercise-detail-add-exercise"
    const val StrengthExerciseDetailDeleteExercise = "test-strength-exercise-detail-delete-exercise"
    const val StrengthExerciseConfigDone = "test-strength-exercise-config-done"
    const val StrengthExerciseConfigCancel = "test-strength-exercise-config-cancel"
    const val StrengthCustomExerciseName = "test-strength-custom-exercise-name"
    const val StrengthCustomExerciseAdd = "test-strength-custom-exercise-add"
    const val StrengthCustomExerciseCancel = "test-strength-custom-exercise-cancel"
    const val StrengthHistoryBack = "test-strength-history-back"

    const val WorkoutPlanBack = "test-workout-plan-back"
    const val WorkoutPlanStartWorkout = "test-workout-plan-start-workout"
    const val WorkoutPlanSaveRunning = "test-workout-plan-save-running"
    const val WorkoutPlanHeartRate = "test-workout-plan-heart-rate"
    const val WorkoutPlanDelete = "test-workout-plan-delete"
    const val WorkoutPlanConfirmDelete = "test-workout-plan-confirm-delete"
    const val WorkoutPlanCancelDelete = "test-workout-plan-cancel-delete"
    const val WorkoutPlanUploadLocalWorkout = "test-workout-plan-upload-local-workout"
    const val RunningTimerToggle = "test-running-timer-toggle"
    const val RunningTimerReset = "test-running-timer-reset"
    const val WorkoutErrorRetry = "test-workout-error-retry"
    const val HeartRatePickerRescan = "test-heart-rate-picker-rescan"
    const val HeartRatePickerDisconnect = "test-heart-rate-picker-disconnect"
    const val HeartRatePickerDismiss = "test-heart-rate-picker-dismiss"

    const val LoginOAuth = "test-login-oauth"
    const val LoginSkip = "test-login-skip"

    const val RunningPlanListManage = "test-running-plan-list-manage"
    const val RunningPlanListBack = "test-running-plan-list-back"
    const val RunningPlanListEmpty = "test-running-plan-list-empty"
    const val RunningPlanManagementBack = "test-running-plan-management-back"
    const val RunningPlanManagementEmpty = "test-running-plan-management-empty"
    const val RunningPlanDelete = "test-running-plan-delete"
    const val RunningPlanConfirmDelete = "test-running-plan-confirm-delete"
    const val RunningPlanCancelDelete = "test-running-plan-cancel-delete"
    const val RunningWorkoutBack = "test-running-workout-back"
    const val RunningPrimaryAction = "test-running-primary-action"
    const val RunningPreviousBlock = "test-running-previous-block"
    const val RunningStopWorkout = "test-running-stop-workout"
    const val RunningStopSave = "test-running-stop-save"
    const val RunningStopDiscard = "test-running-stop-discard"
    const val RunningFinishUpload = "test-running-finish-upload"
    const val RunningFinishUseGarmin = "test-running-finish-use-garmin"
    const val RunningFinishClose = "test-running-finish-close"
    const val RunningConnectHeartRate = "test-running-connect-heart-rate"
    const val LocalRunningWorkoutDelete = "test-local-running-workout-delete"

    const val TrainingCalendarFabMenu = "test-training-calendar-fab-menu"
    const val TrainingCalendarBack = "test-training-calendar-back"
    const val TrainingCalendarMode = "test-training-calendar-mode"
    const val TrainingCalendarSettings = "test-training-calendar-settings"
    const val TrainingCalendarRefresh = "test-training-calendar-refresh"
    const val TrainingCalendarIntervalsAuth = "test-training-calendar-intervals-auth"
    const val TrainingActionRunning = "test-training-action-running"
    const val TrainingActionStrength = "test-training-action-strength"
    const val StrengthPlanSaveDate = "test-strength-plan-save-date"

    fun strengthReadyEntry(entryId: Int): String = "test-strength-ready-entry-$entryId"
    fun strengthOngoingEntry(entryId: Int): String = "test-strength-ongoing-entry-$entryId"
    fun strengthExerciseSearchResult(exerciseId: String): String = "test-strength-exercise-result-$exerciseId"
    fun strengthPlanListRow(planId: Int): String = "test-strength-plan-list-row-$planId"
    fun strengthPlanListStart(planId: Int): String = "test-strength-plan-list-start-$planId"
    fun strengthPlanManagementEdit(planId: Int): String = "test-strength-plan-management-edit-$planId"
    fun strengthPlanExerciseRow(entryId: Int): String = "test-strength-plan-exercise-row-$entryId"
    fun strengthPlanExerciseRestore(entryId: Int): String = "test-strength-plan-exercise-restore-$entryId"
    fun strengthHistoryRow(workoutId: String): String = "test-strength-history-row-$workoutId"
    fun strengthWorkoutSetDetail(entryId: Int, setRecordId: Int): String = "test-strength-workout-set-detail-$entryId-$setRecordId"
    fun strengthChoiceOption(title: String, option: String): String = "test-strength-choice-$title-$option"
    fun strengthRestTimeControl(label: String): String = "test-strength-rest-time-$label"
    fun runningTargetStepper(label: String, direction: String): String = "test-running-target-stepper-$label-$direction"
    fun runningSavedPlan(planId: String): String = "test-running-saved-plan-$planId"
    fun trainingCalendarFabAction(text: String): String = "test-training-calendar-fab-action-$text"
    fun monthlyCalendarDay(day: LocalDate): String = "test-monthly-calendar-day-$day"
    fun monthlyCalendarItem(itemId: String): String = "test-monthly-calendar-item-$itemId"
    fun strengthPlanSaveRow(planId: Int): String = "test-strength-plan-save-row-$planId"
}

internal fun Modifier.debugContentDescription(description: String): Modifier {
    return if (BuildConfig.DEBUG) {
        semantics { contentDescription = description }
    } else {
        this
    }
}
